In [0]:
"""Q1. (Create a program that fulfills the following specification.)

Program Specification

Use the prev. ANN model to predict if the customer with the following information will leave the bank: (Churn_Modelling.csv)

        Geography: France
        Credit Score: 600
        Gender: Male
        Age: 40 years old
        Tenure: 3 years
        Balance: $60000
        Number of Products: 2
        Does this customer have a credit card? Yes
        Is this customer an Active Member: Yes?
        Estimated Salary: $50000

So, should we say goodbye to that customer?"""

In [0]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [0]:
import os
os.getcwd()

'/content'

In [0]:
ls

drive/  sample_data/


In [0]:
os.chdir('/content/drive/My Drive/FORSK')

In [0]:
ls

Churn_Modelling.csv                iris_test.csv
DL_Intro_ANN_Churn_Modeling.ipynb  iris_training.csv
dl_intro_ann_churn_modeling.py


In [0]:
import pandas as pd
dataset =pd.read_csv("Churn_Modelling.csv")

In [0]:
dataset.shape

(10000, 14)

In [0]:
dataset.head()

RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [0]:
import numpy as np
import matplotlib.pyplot as plt

In [0]:
features = dataset.iloc[:,3:13].values
labels = dataset.iloc[:,13].values

In [0]:
features[0]

array([619, 'France', 'Female', 42, 2, 0.0, 1, 1, 1, 101348.88],
      dtype=object)

In [0]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_features_2 = LabelEncoder()
features[:, 2] = labelencoder_features_2.fit_transform(features[:, 2])

#label encoding for gender

In [0]:
features[0]

array([619, 'France', 0, 42, 2, 0.0, 1, 1, 1, 101348.88], dtype=object)

In [0]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_features_1 = LabelEncoder()
features[:, 1] = labelencoder_features_1.fit_transform(features[:, 1])

onehotencoder = OneHotEncoder(categorical_features = [1])
features = onehotencoder.fit_transform(features).toarray()

features = features[:, 1:] #dummy variable trap

In [0]:
features[0]

In [0]:
from sklearn.model_selection import train_test_split
features_train, features_test, labels_train, labels_test = train_test_split(features, labels, test_size = 0.2, random_state = 0)

In [0]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
features_train = sc.fit_transform(features_train)
features_test = sc.transform(features_test)

In [0]:
features_train[0]

array([-0.5698444 ,  1.74309049,  0.16958176, -1.09168714, -0.46460796,
        0.00666099, -1.21571749,  0.8095029 ,  0.64259497, -1.03227043,
        1.10643166])

In [0]:
# Importing the Keras libraries and packages
import keras
from keras.models import Sequential
from keras.layers import Dense

Using TensorFlow backend.


In [0]:
classifier = Sequential()

In [0]:
features.shape

(10000, 11)

In [0]:
#adding the first hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))

Instructions for updating:
Colocations handled automatically by placer.


In [0]:
# Adding the second hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))

# Adding the output layer
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))

# Compiling the ANN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [0]:
classifier.fit(features_train, labels_train, batch_size = 10, epochs = 10)

Instructions for updating:
Use tf.cast instead.
Epoch 1/10
8000/8000 [==============================] - 1s 147us/step - loss: 0.4834 - acc: 0.7959
Epoch 2/10
8000/8000 [==============================] - 1s 103us/step - loss: 0.4278 - acc: 0.7960
Epoch 3/10
8000/8000 [==============================] - 1s 97us/step - loss: 0.4216 - acc: 0.7966
Epoch 4/10
8000/8000 [==============================] - 1s 88us/step - loss: 0.4180 - acc: 0.8246
Epoch 5/10
8000/8000 [==============================] - 1s 90us/step - loss: 0.4153 - acc: 0.8274
Epoch 6/10
8000/8000 [==============================] - 1s 88us/step - loss: 0.4136 - acc: 0.8296
Epoch 7/10
8000/8000 [==============================] - 1s 92us/step - loss: 0.4120 - acc: 0.8311
Epoch 8/10
8000/8000 [==============================] - 1s 88us/step - loss: 0.4110 - acc: 0.8341
Epoch 9/10
8000/8000 [==============================] - 1s 91us/step - loss: 0.4099 - acc: 0.8336
Epoch 10/10
8000/8000 [==============================] - 1s 87us/ste

In [0]:
labels_pred = classifier.predict(features_test)
labels_pred = (labels_pred > 0.5)

In [0]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(labels_test, labels_pred)

In [0]:
cm


array([[1562,   33],
       [ 289,  116]])

In [0]:
x = [0, 0, 600 , 1 , 40 , 3 , 60000 , 2 , 1 ,1 , 50000]
x = np.array(x).reshape(1,-1)

In [0]:
from sklearn.preprocessing import StandardScaler
sc2 = StandardScaler()
x = sc2.fit_transform(x)


In [0]:
x

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [0]:
labels_pred2= classifier.predict(x)
labels_pred2 = (labels_pred2 > 0.5)
labels_pred2

array([[False]])